// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQxWaTbk-HXiWhnTPa_52uZ2D9RFg5CI',
    appId: '1:119004098187:web:b64825d85888586505ae8e',
    messagingSenderId: '119004098187',
    projectId: 'gkfc-bus-tracking',
    authDomain: 'gkfc-bus-tracking.firebaseapp.com',
    storageBucket: 'gkfc-bus-tracking.firebasestorage.app',
    measurementId: 'G-MSFX8N1GR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98ytx7VJj2f8aYkhbFoQT8hsnY_-Dvzc',
    appId: '1:119004098187:android:a9c76f33310cc20f05ae8e',
    messagingSenderId: '119004098187',
    projectId: 'gkfc-bus-tracking',
    storageBucket: 'gkfc-bus-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ5qkHL5NxpIwy2myJvjNTSpuU9q6Pc28',
    appId: '1:119004098187:ios:56ea2598306bcb6805ae8e',
    messagingSenderId: '119004098187',
    projectId: 'gkfc-bus-tracking',
    storageBucket: 'gkfc-bus-tracking.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ5qkHL5NxpIwy2myJvjNTSpuU9q6Pc28',
    appId: '1:119004098187:ios:56ea2598306bcb6805ae8e',
    messagingSenderId: '119004098187',
    projectId: 'gkfc-bus-tracking',
    storageBucket: 'gkfc-bus-tracking.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClQxWaTbk-HXiWhnTPa_52uZ2D9RFg5CI',
    appId: '1:119004098187:web:91628ec1bb6eec7605ae8e',
    messagingSenderId: '119004098187',
    projectId: 'gkfc-bus-tracking',
    authDomain: 'gkfc-bus-tracking.firebaseapp.com',
    storageBucket: 'gkfc-bus-tracking.firebasestorage.app',
    measurementId: 'G-XBH243SSVW',
  );
}
